// Importları yapın
import HomePage from './homePage/page';
import type { Metadata } from "next";

// Metadata tanımını ekleyin
export const metadata: Metadata = {
  title: "product-management.com",
  description: "Generated by create next app",
};

// Sayfa bileşenini döndürün
export default function Page() {
  return <HomePage />;
}
