
import HomePage from './homePage/page';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "product-management.com",
  description: "Generated by create next app",
};

export default function Page() {
  return <HomePage />;
}
